repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3  # Specifies the version/tag of the repo to use
    hooks:
      - id: ruff
        args: [--fix]  # Run ruff to automatically fix issues if possible
      - id: ruff-format  # Run ruff's formatter to fix style/formatting

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.20  # Specifies the version/tag
    hooks:
      - id: uv-lock   # Ensures uv.lock file is kept up-to-date if pyproject.toml changes
